### ISSUE TITLE
Todo List

### ISSUE THREAD

**Issue by JJL772** [JJL772/ek9000-asyn#1]
- [ ] Implement CoE request handling and callbacks
- [ ] Implement CoE record types
- [ ] Read EK9K status and info registers on the fly
- [ ] Read the EK9K terminal layout and compute the PDO address space
- [ ] Finish simple parser for the INST_IO strings
- [ ] Fill out the PDO definitions for the terminal PDOs (pdo.h)
- [ ] Re-implement the diagnostic iocsh functions
- [ ] Test and verify the implementation
